version: 2
updates:

- package-ecosystem: "maven"
  directory: "/Spigot"
  schedule:
    interval: "daily"
  assignees:
    - "thelooter"

-  package-ecosystem: "maven"
   directory: "/Engine"
   schedule:
     interval: "daily"
   assignees:
     - "thelooter"